### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ivan-ristovic/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by ivan-ristovic** [comment]
Thank you @unixorn .

I have added the LICENSE as per request, cheers!

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/761 as ristovic theme (zsh-theme is a bit too generic).

If you rename the repo to something else, either add an issue for me to rename it or make a PR, thanks!

**Comment by ivan-ristovic** [comment]
I would appreciate if you renamed it to "xris47" since it is named like that in the repository. 

Thanks

**Comment by unixorn** [comment]
Sure. Do you want to rename the repository first?

**Comment by ivan-ristovic** [comment]
Yes, I have done so.

Thank you.

**Comment by unixorn** [comment]
Renamed in https://github.com/unixorn/awesome-zsh-plugins/pull/762
