### ISSUE TITLE
how zplug manage this theme

### ISSUE THREAD

**Issue by oison111** [ivan-ristovic/zsh-theme#2]
zplug "themes/xris47.zsh-theme", as:theme, from:oh-my-zsh

but it doesn't work

**Comment by ivan-ristovic** [comment]
This theme is not present in the `oh-my-zsh` repository. You can install it using zplug like so:
```
zplug "ivan-ristovic/xris47.zsh-theme"
```
If problems persist, please re-open. Please note that I haven't been maintaining this theme for some time now, since I have swapped to p10k.

**Comment by oison111** [comment]
Thank you!
At the beginning, MY problem was that I didn't know how to change the theme. I looked at the previous issue and found that there was something wrong with my writing method
That's what I wrote earlier
zplug "themes/pygmalion.zsh-theme", as:theme, form:oh-my-zsh


***@***.***
 
From: Ivan Ristović
Date: 2022-04-04 03:47
To: ivan-ristovic/xris47.zsh-theme
CC: oison111; Author
Subject: Re: [ivan-ristovic/xris47.zsh-theme] how zplug manage this theme (Issue #2)
This theme is not present in the oh-my-zsh repository. You can install it using zplug like so:
zplug "ivan-ristovic/xris47.zsh-theme"

**Comment by oison111** [comment]
***@***.***
 
Sorry to bother you, I installed this theme according to your tutorial, but it doesn't seem to take effect




I also tried following your instructions to install the script into oh-my-zsh and write it in ~/.zshrc
zplug "themes/xris47", as:theme, from:oh-my-zsh
But it didn't work




From: Ivan Ristović
Date: 2022-04-04 03:47
To: ivan-ristovic/xris47.zsh-theme
CC: oison111; Author
Subject: Re: [ivan-ristovic/xris47.zsh-theme] how zplug manage this theme (Issue #2)
This theme is not present in the oh-my-zsh repository. You can install it using zplug like so:
zplug "ivan-ristovic/xris47.zsh-theme"

**Comment by ivan-ristovic** [comment]
> Sorry to bother you

No worries.

> I also tried following your instructions to install the script into oh-my-zsh and write it in ~/.zshrc
> zplug "themes/xris47", as:theme, from:oh-my-zsh
> But it didn't work

I am not sure I understand. As per my comment, the way to install it via zplug is to reference this directory. It does not exist in the `themes` folder of `oh-my-zsh` installation by default (unless you cloned it there already?). If you have the theme in your `themes` folder (double-check it), then adding the following to your `.zshrc` must load the theme (as any other theme that is present there):
```
ZSH_THEME="xris47"
```

**Comment by ivan-ristovic** [comment]
In order to better diagnose the issue, could you please provide the details of your environment (where the theme is located), and parts of your `.zshrc` (perhaps the entire file with sensitive parts removed)?

**Comment by oison111** [comment]
> > Sorry to bother you
> 
> No worries.
> 
> > I also tried following your instructions to install the script into oh-my-zsh and write it in ~/.zshrc
> > zplug "themes/xris47", as:theme, from:oh-my-zsh
> > But it didn't work
> 
> I am not sure I understand. As per my comment, the way to install it via zplug is to reference this directory. It does not exist in the `themes` folder of `oh-my-zsh` installation by default (unless you cloned it there already?). If you have the theme in your `themes` folder (double-check it), then adding the following to your `.zshrc` must load the theme (as any other theme that is present there):
> 
> ```
> ZSH_THEME="xris47"
> ```
![image](https://user-images.githubusercontent.com/102855127/161470681-f19083c4-525d-4f91-b99b-9f433914f042.png)

**Comment by oison111** [comment]
> > > Sorry to bother you
> > 
> > 
> > No worries.
> > > I also tried following your instructions to install the script into oh-my-zsh and write it in ~/.zshrc
> > > zplug "themes/xris47", as:theme, from:oh-my-zsh
> > > But it didn't work
> > 
> > 
> > I am not sure I understand. As per my comment, the way to install it via zplug is to reference this directory. It does not exist in the `themes` folder of `oh-my-zsh` installation by default (unless you cloned it there already?). If you have the theme in your `themes` folder (double-check it), then adding the following to your `.zshrc` must load the theme (as any other theme that is present there):
> > ```
> > ZSH_THEME="xris47"
> > ```
> 
> ![image](https://user-images.githubusercontent.com/102855127/161470681-f19083c4-525d-4f91-b99b-9f433914f042.png


The second method, I referred to your Installation
![image](https://user-images.githubusercontent.com/102855127/161471128-0eea991b-8252-4d1f-8299-ff06b6f43a88.png)


According to your Installation, I installed this theme into oh-my-zsh and loaded it with Zplug, as you can see, it didn't work either
![image](https://user-images.githubusercontent.com/102855127/161471017-4b4dbf18-a712-4f6d-956d-60fbc77b367c.png)

**Comment by ivan-ristovic** [comment]
Hmm I am not sure what the problem is here, I cannot reproduce that on my end... I assume other themes are working properly? You have the latest zsh/omz?

**Comment by oison111** [comment]
> Hmm I am not sure what the problem is here, I cannot reproduce that on my end... I assume other themes are working properly? You have the latest zsh/omz?

I am using centos8 - stream,
ZSH, OH-my-zsh and Zplug have been installed according to the official website documents for two days.
It should be the latest version,
I have two more ways to test this,
One is to use oh-my-zsh to load themes instead of Zplug,
another is try using Zplug to load other themea that are not in oh-my-zsh
![image](https://user-images.githubusercontent.com/102855127/161555329-877a03b9-8b21-4fbe-9235-abcdcf6de2a7.png)
![image](https://user-images.githubusercontent.com/102855127/161555900-9089dbb8-df2c-4f7d-b9d3-f21e20edbb16.png)
![image](https://user-images.githubusercontent.com/102855127/161556394-b892abac-7141-40c6-82f1-074fa4c06345.png)

**Comment by ivan-ristovic** [comment]
Thank you for the detailed description. I will look into it and get back to you as soon as I am able to reproduce it.

**Comment by ivan-ristovic** [comment]
The problem seems to be that zplug does not put it into the `themes` directory of oh-my-zsh (which makes sense, it cannot know that). For me it was downloaded in: 
```
~/.zplug/repos/ivan-ristovic/zsh-theme/xris47.zsh-theme
```
So, this has to be either linked to the `themes` folder, or manually set as `ZSH_THEME` env var, in order for OMZ to see it.

I searched about this on zplug repository and there doesn't seem to be a prettier solution.
